/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luxor_hdfs_common_NamedPipe */

#ifndef _Included_luxor_hdfs_common_NamedPipe
#define _Included_luxor_hdfs_common_NamedPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luxor_hdfs_common_NamedPipe
 * Method:    createPipeInternal
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luxor_hdfs_common_NamedPipe_createPipeInternal
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
